# -*- coding: utf-8 -*-
"""BankNote

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgCg3XyVglchPzH7sQ17kxH9zmIbh87N
"""

#Importing Libraries

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle

from google.colab import drive
drive.mount('/content/drive')

Bank_data=pd.read_csv("/content/drive/MyDrive/MLops_activity/BankNote_Authentication.csv")

x=Bank_data.iloc[:,:-1]
y=Bank_data.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=50)

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

pickle_out = open("BankNote.pkl","wb")
pickle.dump(clf, pickle_out)
pickle_out.close()

clf.predict([[2,3,4,1]])